import NavBar from "../components/navBar";

// export const metadata = {
//   title: 'Next.js Projec1',
//   description: 'Generated by Next.js',
// }
const RootLayout = ({ children }) => {

 return (
    <html lang="en">
      <head>
        <title>Next Project1</title>
      </head>
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )

}

export default RootLayout;
